all:
	haxe -cp "/" -lib format -lib nme --remap flash:nme -cp . -main Graph --times -cpp cpp
#haxelib run nme update graph.nmml linux
#	haxelib run nme build graph.nmml linux

run:
	./cpp/Graph 5
#	./Export/cpp/linux/bin/MyApplication 5
