run:
	./cpp/Graph 5
#	./Export/cpp/linux/bin/MyApplication 5

build:
	haxe -lib format -main Graph --times -cpp cpp -dce full -D HXCPP_M64 -D haxe3
#haxelib run nme update graph.nmml linux
#	haxelib run nme build graph.nmml linux

