#!/bin/bash

function count() {

	FILES=`find . -type f -name "*."$1`
	COUNT=0

	for file in $FILES
	do
	    line=`wc -l $file | grep -o '^[ \\t]*[0-9][0-9]*'`
	    COUNT=$((COUNT+line))
	done

	echo $1" source = "$COUNT" lines"

}

count cx
count hx
