#!/bin/bash

MODULES="nape-symbolic nape-hacks"

dir=$(pwd)
ssh-add ~/.ssh/id_rsa

cd $dir

#core
echo "core"
rm -rf nape.tar.gz
tar cvfz nape.tar.gz cx-src Makefile version server-remotes fix-externs
scp nape.tar.gz deltaluca.me.uk:nape.tar.gz
ssh deltaluca.me.uk <<-EOT
	./nape-release
EOT

#modules
for module in $MODULES; do
	echo "$module"
	cd ../$module	

	make tar
	scp $module.tar.gz deltaluca.me.uk:$module.tar.gz
	ssh deltaluca.me.uk <<-EOT
		./nape-module $module
	EOT

	cd ../nape
done

exit
