NAPELIB = $(NAPE)/haxe_debug_nape.swf
NAPELIB = ../../bin/release/haxe_release_nape.swf

build:
	haxe -swf-lib $(NAPELIB) -swf-header 800:400:40:333333 -swf WaterBalls.swf -cp . -main WaterBalls -swf-version 11
	fp WaterBalls.swf 
