run: build
	debugfp Portals.swf

build:
	haxe 		-cp "/" -cp . -cp ../common	-lib nape -swf-header 600:450:60:333333 		-swf-version 10.1 		-main Portals 		-swf Portals.swf --dead-code-elimination -debug
