run: build
	debugfp DestructableTerrain.swf

build:
	haxe 		-cp "/" -cp . -cp ../common 		-lib nape 		-swf-header 800:600:60:333333 		-swf-version 10.1 		-main DestructableTerrain 		-swf DestructableTerrain.swf -debug --no-inline
