#!/bin/bash

excludes="ConstraintStressTest"

dirs=`find . -type d -wholename "\./*"`

rm -rf ../doc-gen/xml/demo
rm -rf ../doc-gen/doc/swf

for d in $dirs
do
	if [ -e "$d/Makefile" ] || [ -e "$d/makefile" ]
	then
		echo " >> demo $d"
		name=`echo ${d:2}`

        ind=`awk -v a="$excludes" -v b="$name" 'BEGIN{print index(a,b)}'`
        if [ "$ind" -ne 0 ]; then
            echo " (Excluded) "
            continue
        fi

		cd $d
		cur=`pwd`

		cd ../../doc-gen/xml/
		mkdir -p demo
		cp $cur/$name.xml demo/
		cp $cur/$name.as demo/
		cp $cur/$name.hx demo/

		mkdir -p ../doc/swf
		cd ../doc/swf/
		cp $cur/$name.swf .
		cd $cur/../
	fi
done

