#!/bin/bash

# template name width height fps bgcol

mkdir $1
cd $1

cat > Makefile << EOT
run: build
	fp $1.swf

build:
	haxe \
		-cp "/" -cp . -cp ../common \
		-lib nape \
		-D NAPE_RELEASE_BUILD \
		-swf-header $2:$3:$4:$5 \
		-swf-version 10 \
		-main $1 \
		-swf $1.swf
EOT

cat > $1.hx << EOT
package;

import nape.space.Space;
import nape.phys.Body;
import nape.phys.BodyType;
import nape.shape.Circle;
import nape.shape.Polygon;
import nape.geom.Vec2;
import nape.util.BitmapDebug;

import FixedStep;

class $1 extends FixedStep {
	static function main() new $1()
	function new() {
		super(1/$4);

		var space = new Space(new Vec2(0,400));
		var debug = new BitmapDebug($2,$3,0x$5);
		addChild(debug.display);

		run(function (dt) {
			debug.clear();
			space.step(dt);
			debug.draw(space);
			debug.flush();
		});
	}
}

EOT

cat > $1.as << EOT
package {
	
	//not yet written!
}
EOT

cat > $1.xml << EOT
<?xml version="1.0" encoding="utf-8" ?>
<data>

<swf name="$1" package="">
	<short>
		
	</short>
	<long>
		<br/>
		
		
		<br/>
		<br/>
		<swf centre="true" file="$1.swf" width="$2" height="$3"/>
		<br/>
		<br/>
		<link type="relative" anchor="AS3">AS3 Source</link><br/>
		<link type="relative" anchor="Haxe">Haxe Source</link><br/>
		<br/>
		<hr/>
		<br/>
		<anch name="AS3"/><text class="header2">AS3 Source</text>
		<br/>
		<!-- executed from /doc-gen/ with .as/.hx as /doc-gen/xml/demo/ -->
		<code file="xml/demo/$1.as"/>
		<br/>
		<hr/>
		<br/>
		<anch name="Haxe"/><text class="header2">Haxe Source</text>
		<br/>
		<code file="xml/demo/$1.hx"/>
		<br/>
	</long>
</swf>

</data>
EOT
