#!/bin/bash

dirs=`find . -type d -wholename "\./*"`

total=0
pass=0

for d in $dirs
do
	if [ -e "$d/Makefile" ] || [ -e "$d/makefile" ]
	then
		echo " >> testing demo $d"
		cd $d
		make build
		if [ "$?" = "0" ]
		then
			pass=$((pass+1))
		fi
		total=$((total+1))
		cd ../
	fi
done

echo ""
echo " Total tests: $total"
echo " Passed: $pass"
fail=$((total-pass))
echo " Failed: $fail"

[ "$fail" = "0" ]
exit
